[package]
name = "holomorphic-visualizer"
version = "0.1.0"
authors = ["Frederik Semmel <frederiksemmel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14.1"
